### ISSUE TITLE
Align with `fetch`

### ISSUE THREAD

**Issue by vanthome** [n-fuse/pajax#4]
Seems like we are not the only ones who think promised Ajax is a good thing.
This upcoming spec is already implemented in Chrome ;)

https://github.com/github/fetch

**Comment by Dani723** [comment]
@vanthome 
The new pajax 0.3 result object was designed to be pretty close to the fetch() result object.
A switch to fetch() would bring a lot of great possibilities.

We could get rid of the internal xhr-promise-wrapper, be 100% interface compatible to the fetch() results and still keep the pajax-advantages like option-chaining, pipelets and extensibility.
