### ISSUE TITLE
add default Pipelets and base url to all verbs

### ISSUE THREAD

**Issue by devmondo** [n-fuse/pajax#5]
hi, awesome library.

what is the best approach to add Pipelets and base url along other default headers, etc... to all verbs POST,GET, etc...

thx in advanced.

**Comment by Dani723** [comment]
Hi, thanks a lot :)

You can provide default options in the ctor when creating an instance

```js
var pajax = new Pajax({
  baseURL: 'http://127.0.0.1:3500',
  headers: {
    'Authorization': 'foo'
  }
});
```

Using pipelets for every request, can be achieved by overriding the request method in the pajax class:

```js
class MyPajax extends Pajax {
  request(...args) {
    return super.request(...args).before(req=>{
      // do stuff
      return req;
    });
  }
}

var pajax = new MyPajax({
  ...
});

```

We're currently working on pajax 0.4 which unifies the chain configuration for pajax and request instances.

```js
// For all all request done with the pajax instance
var pajax = new Pajax()
            .setBaseURL('http://127.0.0.1:3500')
            .header('Authorization', 'foo')
            .before(req=>{
              // do stuff
              return req;
            });

var pajax2 = new Pajax()
// For only this request
var pajax2.setBaseURL('http://127.0.0.1:3500')
          .header('Authorization', 'foo')
          .before(req=>{
            // do stuff
            return req;
          })
          .send()
          .then(...);
```
It will be released this week (hopefully).

See https://github.com/n-fuse/pajax/tree/0.4

**Comment by devmondo** [comment]
man this is awesome reply, i really appreciate the detailed answer, please release v 0.4 ASAP :)
